17 clean up motif tooltip
gymrek-lab/webstr pull request #28
Opened 2024-08-07 19:28 UTC by ciarareeve

This pull request enhances the STR table and the interactive Plotly chart on the search page. Key updates include:

1. **Responsive Plotly Chart:**
   - The Plotly chart now adjusts to screen width changes, improving experience across devices.

2. **Table Replacement with Card-Based Layout:**
   - The original table is replaced with a card-based layout to fix formatting issues and improve click region control. The card layout is modular and flexible, making it easier to manage the appearance and behavior of each data item. This also prevents unintended interactions and allows for future functionality enhancements.

3. **Improved Tooltip/Popover Integration:**
   - Integrated Bootstrap popovers for additional information on hover.

2024-08-08 20:11 UTC, gymreklab requested changes
I tried this out and it works great! I made some minor cleanup requests for WebSTR.py then we can merge

2024-08-08 20:29 UTC, ciarareeve commented on WebSTR/WebSTR.py
> +    print("Region Data (dictionary format):", data)
yes i think this was accidentally left over from part of a debug process.  just pushed changes.

2024-08-08 20:29 UTC, ciarareeve commented on WebSTR/WebSTR.py
> -    server.run(debug=FLASK_DEBUG, host=args.host, port=args.port)
Just set it back to FLASK_DEBUG and pushed.  Thank you!

2024-08-09 03:26 UTC, gymreklab submitted a review, later dismissed
Thanks for making these changes!

2024-08-09 03:31 UTC, gymreklab approved these changes

2024-08-09 03:32 UTC, merged